// Generated by CoffeeScript 1.12.3
var ChEMBLSketch, Target, elastic_json_data, elastic_query_data, elastic_query_size, elastic_query_url, loadElasticJSON, startSketch;

elastic_json_data = null;

elastic_query_size = 100;

Target = (function() {
  Target.MOLECULE_KNOWN_IDS = {};

  Target.MAX_COUNT = Number.NEGATIVE_INFINITY;

  Target.reduceData = function(targets) {
    var i, j, k, l, len, len1, len2, len3, molecule_id, molecule_id_i, reduced_targets, ref, ref1, target_i;
    reduced_targets = [];
    ref = _.keys(Target.MOLECULE_KNOWN_IDS);
    for (i = 0, len = ref.length; i < len; i++) {
      molecule_id = ref[i];
      if (Target.MOLECULE_KNOWN_IDS[molecule_id] <= elastic_query_size / 10) {
        delete Target.MOLECULE_KNOWN_IDS[molecule_id];
        for (j = 0, len1 = targets.length; j < len1; j++) {
          target_i = targets[j];
          delete target_i.molecule_counts[molecule_id];
        }
      }
    }
    for (k = 0, len2 = targets.length; k < len2; k++) {
      target_i = targets[k];
      ref1 = _.keys(target_i.molecule_counts);
      for (l = 0, len3 = ref1.length; l < len3; l++) {
        molecule_id_i = ref1[l];
        if (target_i.molecule_counts[molecule_id_i] === 0) {
          delete target_i.molecule_counts[molecule_id_i];
        }
      }
      if (_.keys(target_i.molecule_counts).length > elastic_query_size / 10) {
        reduced_targets.push(target_i);
      }
    }
    return reduced_targets;
  };

  Target.parseElasticJSON = function(elasticJson) {
    var bucket_i, bucket_j, i, j, len, len1, ref, ref1, target_i, target_id_i, targets;
    targets = [];
    ref = elasticJson.aggregations.group_by_target.buckets;
    for (i = 0, len = ref.length; i < len; i++) {
      bucket_i = ref[i];
      target_id_i = bucket_i.key;
      target_i = new Target(target_id_i);
      targets.push(target_i);
      ref1 = bucket_i.group_by_compound.buckets;
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        bucket_j = ref1[j];
        target_i.addCompoundCount(bucket_j.key, bucket_j.doc_count);
      }
    }
    targets = Target.reduceData(targets);
    return targets;
  };

  Target.HSB_HUE = 160;

  Target.CELL_SIZE = 5;

  function Target(target_id) {
    this.target_id = target_id;
    this.molecule_counts = {};
  }

  Target.prototype.addCompoundCount = function(molecule_id, doc_count) {
    this.molecule_counts[molecule_id] = doc_count;
    if (!_.has(Target.MOLECULE_KNOWN_IDS, molecule_id)) {
      Target.MOLECULE_KNOWN_IDS[molecule_id] = 0;
    }
    Target.MOLECULE_KNOWN_IDS[molecule_id] += 1;
    if (doc_count > Target.MAX_COUNT) {
      return Target.MAX_COUNT = doc_count;
    }
  };

  Target.prototype.draw = function(p, yPos, cellHeight, xStart) {
    var cellX, doc_count, i, index, len, molecule_id, molecules, results, sat, val;
    molecules = _.keys(Target.MOLECULE_KNOWN_IDS);
    results = [];
    for (index = i = 0, len = molecules.length; i < len; index = ++i) {
      molecule_id = molecules[index];
      cellX = p.map(index, 0, molecules.length - 1, 0, Target.CELL_SIZE * molecules.length);
      doc_count = _.has(this.molecule_counts, molecule_id) ? this.molecule_counts[molecule_id] : 0;
      if (doc_count !== 0) {
        sat = p.floor(p.map(doc_count, 0, 15, 5, 100)) % 100;
        val = 90;
        p.colorMode(p.HSB);
        p.noStroke();
        p.fill(p.color(Target.HSB_HUE, sat, val));
        results.push(p.rect(cellX, yPos, Target.CELL_SIZE - 1, Target.CELL_SIZE - 1));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  return Target;

})();

ChEMBLSketch = function(p) {
  var canvas, plotSize, targets;
  console.log(elastic_json_data);
  plotSize = 800;
  targets = null;
  canvas = null;
  p.preload = function() {
    return targets = Target.parseElasticJSON(elastic_json_data);
  };
  p.setup = function() {
    canvas = p.createCanvas(plotSize, plotSize);
    console.log(targets);
    return p.noLoop();
  };
  return p.draw = function() {
    var i, index, len, results, target_i, xPlotEnd, xPlotStart, yPlotEnd, yPlotStart, yPos;
    p.background(0);
    p.fill(0, 255, 0);
    yPlotStart = 0;
    yPlotEnd = p.height;
    xPlotStart = 0;
    xPlotEnd = p.width;
    results = [];
    for (index = i = 0, len = targets.length; i < len; index = ++i) {
      target_i = targets[index];
      yPos = p.map(index, 0, targets.length - 1, Target.CELL_SIZE * targets.length, yPlotStart);
      results.push(target_i.draw(p, yPos, Target.CELL_SIZE, xPlotStart));
    }
    return results;
  };
};

startSketch = function(elastic_data) {
  var sketch;
  elastic_json_data = elastic_data;
  return sketch = new p5(ChEMBLSketch);
};

elastic_query_url = "https://wwwdev.ebi.ac.uk/chembl/glados-es/chembl_activity/_search";

elastic_query_data = {
  aggs: {
    group_by_target: {
      terms: {
        field: "target_chembl_id",
        size: elastic_query_size
      },
      aggs: {
        group_by_compound: {
          terms: {
            field: "molecule_chembl_id",
            size: elastic_query_size
          },
          aggs: {
            activity_count: {
              value_count: {
                field: "activity_id"
              }
            }
          }
        }
      }
    }
  }
};

loadElasticJSON = function(url, data, success_callback) {
  return $.ajax(elastic_query_url, {
    data: JSON.stringify(elastic_query_data),
    method: 'POST',
    success: success_callback,
    error: function(jqXHR, textStatus, errorThrown) {
      console.log(textStatus);
      console.log(errorThrown);
      return alert("Error retrieving data!");
    }
  });
};

$(document).ready(function() {
  $(document).ajaxStart(function() {
    return $('body').append("<div id='ajax_loading'>Loading data . . .</div>");
  });
  $(document).ajaxStop(function() {
    return $('#ajax_loading').remove();
  });
  return loadElasticJSON(elastic_query_url, elastic_query_data, startSketch);
});

//# sourceMappingURL=chembl-sketch.js.map
